#查看是否创建成功 成功是会多个admin
#kubectl get serviceaccount -n kube-system
#查看详情
#kubectl describe serviceaccount admin -n kube-system
#接着上面
  #kubectl get secret -n kube-system
  #会多出来一个
    #admin-token-clw55                kubernetes.io/service-account-token   3      5m37s
  #或者
  #kubectl get secret -n kube-system|grep admin-token
  #可以查出名称
    #后可查看详情
    # kubectl get secret admin-token-clw55 -o jsonpath={.data.token} -n kube-system |base64 -d

  #查看详情
  #kubectl describe secret admin-token-clw55 -n kube-system




apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  name: admin
  namespace: kube-system


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-admin
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
