---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    k8s-app: liveness
spec:
  containers:
    - name: liveness
      image: cnych/liveness
      args:
        - /server
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5