---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    k8s-app: liveness
spec:
  containers:
    - name: liveness
      image: busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30;rm -rf /tmp/healthy;sleep 600;
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5