apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
  labels:
    app: nginx-deploy
spec:
  replicas: 3
  minReadySeconds: 5
  template:
    metadata:
      name: nginx-deploy
      labels:
        app: nginx-deploy
    spec:
      containers:
        - name: nginx-deploy
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: nginx-deploy
